function format_ieee_axes(ax)
% format_ieee_axes Apply compact IEEE-style axes formatting.

set(ax, ...
    'FontName', 'Times New Roman', ...
    'FontSize', 9, ...
    'LineWidth', 0.8, ...
    'Box', 'on', ...
    'GridAlpha', 0.18, ...
    'MinorGridAlpha', 0.08);
end
