"""
B3 learned-Q export.

Reads the composite angular-separation scan generated by
matlab/genB3_operator_response.m and exports the learned discriminative
matrix Q for each sample. This script does not compute RMSE/PoR.
"""

from __future__ import annotations

import argparse
import os
import re

import h5py
import numpy as np
import torch

from ours_test_common import (
    DEVICE,
    load_model_from_checkpoint,
    normalize_covariance_array,
)


DEFAULT_DATA_PATH = "../data/B3/B3_OperatorResponse_QPn.h5"
DEFAULT_MODEL_PATH = "ours_model.pth"
DEFAULT_OUT_PATH = "../data/B3/B3_OperatorResponse_Q.h5"


def parse_delta_group(name: str) -> float:
    match = re.search(r"Delta_([0-9]+(?:p[0-9]+)?)deg", name)
    if not match:
        return float("inf")
    return float(match.group(1).replace("p", "."))


def export_q_group(model, cov: np.ndarray, batch_size: int) -> np.ndarray:
    chunks = []
    model.eval()
    with torch.no_grad():
        for start in range(0, cov.shape[0], batch_size):
            end = min(start + batch_size, cov.shape[0])
            x = torch.from_numpy(cov[start:end]).float().to(DEVICE)
            q = model.make_Q(x).detach().cpu().numpy().astype(np.complex64)
            chunks.append(q)
    return np.concatenate(chunks, axis=0)


def copy_if_exists(fin: h5py.File, fout: h5py.File, name: str) -> None:
    if name in fin:
        fout.create_dataset(name, data=np.array(fin[name]))


def main() -> None:
    parser = argparse.ArgumentParser(description="Export learned Q for B3.")
    parser.add_argument("--data", default=DEFAULT_DATA_PATH)
    parser.add_argument("--model", default=DEFAULT_MODEL_PATH)
    parser.add_argument("--out", default=DEFAULT_OUT_PATH)
    parser.add_argument("--rank", type=int, default=8)
    parser.add_argument("--batch_size", type=int, default=128)
    args = parser.parse_args()

    print(f"Device: {DEVICE}")
    print(f"Loading Ours model from {args.model}...")
    model, _angle_grid, m, rank, _metadata = load_model_from_checkpoint(args.model, args.rank)
    print(f"Model loaded. m={m}, rank={rank}")

    out_dir = os.path.dirname(args.out)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)
    if os.path.exists(args.out):
        os.remove(args.out)

    with h5py.File(args.data, "r") as fin, h5py.File(args.out, "w") as fout:
        for key, value in fin.attrs.items():
            fout.attrs[key] = value
        fout.attrs["source_data"] = args.data
        fout.attrs["model"] = args.model
        fout.attrs["description"] = "Learned Q export for B3 operator-response analysis"

        copy_if_exists(fin, fout, "delta_theta_vec")
        copy_if_exists(fin, fout, "angle_scan")

        groups = sorted(
            [name for name, obj in fin.items() if isinstance(obj, h5py.Group)],
            key=parse_delta_group,
        )
        print(f"Found {len(groups)} Delta groups.")

        for group_name in groups:
            gin = fin[group_name]
            cov = normalize_covariance_array(np.array(gin["sam"]))
            if cov.shape[-1] != m:
                raise ValueError(f"{group_name}: data M={cov.shape[-1]} does not match model m={m}")
            print(f"{group_name}: exporting Q for {cov.shape[0]} samples...", flush=True)
            q = export_q_group(model, cov, args.batch_size)

            gout = fout.create_group(group_name)
            gout.create_dataset("Q_real", data=q.real.astype(np.float32))
            gout.create_dataset("Q_imag", data=q.imag.astype(np.float32))
            if "angles" in gin:
                gout.create_dataset("angles", data=np.array(gin["angles"]))
            for key, value in gin.attrs.items():
                gout.attrs[key] = value

    print(f"Saved learned Q to {args.out}")


if __name__ == "__main__":
    main()
