"""
B4 ablation Q export.

Reads data generated by matlab/generateB4_operator_ablation.m and exports Q matrices for
Projector fitting, Null-only, and Full objective models.
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

import h5py
import numpy as np
import torch

from ours_test_common import (
    DEVICE,
    load_model_from_checkpoint,
    normalize_covariance_array,
)


DEFAULT_DATA_PATH = "../data/B4/B4_OperatorAblation_QPn_K2.h5"
DEFAULT_OUT_PATH = "../data/B4/B4_Ablation_Q_K2.h5"
DEFAULT_PROJECTOR_MODEL = "ablation_models/B4_projector_fitting.pth"
DEFAULT_NULL_MODEL = "ablation_models/B4_null_only.pth"
DEFAULT_FULL_MODEL = "ablation_models/B4_full.pth"
DEFAULT_FULL_FALLBACK = "ours_model.pth"


def resolve_path(path: str, base_dir: Path) -> Path:
    p = Path(path)
    if p.is_absolute():
        return p
    return base_dir / p


def export_q_group(model, cov: np.ndarray, batch_size: int) -> np.ndarray:
    chunks = []
    model.eval()
    with torch.no_grad():
        for start in range(0, cov.shape[0], batch_size):
            end = min(start + batch_size, cov.shape[0])
            x = torch.from_numpy(cov[start:end]).float().to(DEVICE)
            q = model.make_Q(x).detach().cpu().numpy().astype(np.complex64)
            chunks.append(q)
    return np.concatenate(chunks, axis=0)


def copy_if_exists(fin: h5py.File, fout: h5py.File, name: str) -> None:
    if name in fin:
        fout.create_dataset(name, data=np.array(fin[name]))


def copy_group_attrs(gin: h5py.Group, gout: h5py.Group) -> None:
    for key, value in gin.attrs.items():
        gout.attrs[key] = value


def collect_sample_groups(fin: h5py.File) -> list[str]:
    sample_groups: list[str] = []

    def visitor(name: str, obj) -> None:
        if isinstance(obj, h5py.Group) and "sam" in obj:
            sample_groups.append(name)

    fin.visititems(visitor)
    return sorted(sample_groups)


def load_named_models(args: argparse.Namespace, script_dir: Path):
    model_specs = {
        "projector": resolve_path(args.projector_model, script_dir),
        "null_only": resolve_path(args.null_model, script_dir),
        "full": resolve_path(args.full_model, script_dir),
    }
    if not model_specs["full"].exists():
        fallback = resolve_path(args.full_fallback, script_dir)
        print(f"Full model {model_specs['full']} not found; using fallback {fallback}")
        model_specs["full"] = fallback

    models = {}
    model_meta = {}
    for name, path in model_specs.items():
        if not path.exists():
            raise FileNotFoundError(f"Missing {name} model: {path}")
        print(f"Loading {name} model from {path}...")
        model, _angle_grid, m, rank, metadata = load_model_from_checkpoint(str(path), args.rank)
        models[name] = model
        model_meta[name] = {"path": str(path), "m": m, "rank": rank, "metadata": metadata}
        print(f"  {name}: m={m}, rank={rank}")
    return models, model_meta


def main() -> None:
    parser = argparse.ArgumentParser(description="Export B4 ablation Q matrices.")
    parser.add_argument("--data", default=DEFAULT_DATA_PATH)
    parser.add_argument("--out", default=DEFAULT_OUT_PATH)
    parser.add_argument("--projector_model", default=DEFAULT_PROJECTOR_MODEL)
    parser.add_argument("--null_model", default=DEFAULT_NULL_MODEL)
    parser.add_argument("--full_model", default=DEFAULT_FULL_MODEL)
    parser.add_argument("--full_fallback", default=DEFAULT_FULL_FALLBACK)
    parser.add_argument("--rank", type=int, default=8)
    parser.add_argument("--batch_size", type=int, default=128)
    args = parser.parse_args()

    script_dir = Path(__file__).resolve().parent
    data_path = resolve_path(args.data, script_dir)
    out_path = resolve_path(args.out, script_dir)

    print(f"Device: {DEVICE}")
    print(f"Data: {data_path}")
    models, model_meta = load_named_models(args, script_dir)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    if out_path.exists():
        out_path.unlink()

    with h5py.File(data_path, "r") as fin, h5py.File(out_path, "w") as fout:
        for key, value in fin.attrs.items():
            fout.attrs[key] = value
        fout.attrs["source_data"] = str(data_path)
        fout.attrs["description"] = "B4 ablation Q export for projector/null-only/full objectives"
        for name, meta in model_meta.items():
            fout.attrs[f"{name}_model"] = meta["path"]
            fout.attrs[f"{name}_rank"] = meta["rank"]

        copy_if_exists(fin, fout, "delta_theta_vec")
        copy_if_exists(fin, fout, "theta_vec")
        copy_if_exists(fin, fout, "angle_scan")
        copy_if_exists(fin, fout, "K_vec")

        groups = collect_sample_groups(fin)
        print(f"Found {len(groups)} sample groups.")

        for group_name in groups:
            gin = fin[group_name]
            cov = normalize_covariance_array(np.array(gin["sam"]))
            print(f"{group_name}: exporting Q for {cov.shape[0]} samples...", flush=True)
            gout = fout.require_group(group_name)
            if "angles" in gin:
                gout.create_dataset("angles", data=np.array(gin["angles"]))
            for key, value in gin.attrs.items():
                gout.attrs[key] = value

            parent_parts = group_name.split("/")[:-1]
            for depth in range(1, len(parent_parts) + 1):
                parent_name = "/".join(parent_parts[:depth])
                if parent_name in fin:
                    copy_group_attrs(fin[parent_name], fout.require_group(parent_name))

            for model_name, model in models.items():
                _meta = model_meta[model_name]
                if cov.shape[-1] != _meta["m"]:
                    raise ValueError(
                        f"{group_name}: data M={cov.shape[-1]} does not match "
                        f"{model_name} model m={_meta['m']}"
                    )
                q = export_q_group(model, cov, args.batch_size)
                qgrp = gout.create_group(model_name)
                qgrp.create_dataset("Q_real", data=q.real.astype(np.float32))
                qgrp.create_dataset("Q_imag", data=q.imag.astype(np.float32))

    print(f"Saved B4 ablation Q to {out_path}")


if __name__ == "__main__":
    main()
